# Generated by Django 5.2.9 on 2025-12-09 06:15

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.CharField(default='default', max_length=50)),
                ('date_of_birth', models.DateField()),
                ('language', models.CharField(choices=[('HINDI', 'Hindi'), ('TAMIL', 'Tamil'), ('GUJARATI', 'Gujarati'), ('PUNJABI', 'Punjabi'), ('TELUGU', 'Telugu'), ('MALAYALAM', 'Malayalam')], default='HINDI', max_length=20)),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('total_points', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'children',
            },
        ),
    ]
