# Generated by Django 5.2.9 on 2025-12-09 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['user'], name='children_user_id_461969_idx'),
        ),
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['language', 'level'], name='children_languag_0f4695_idx'),
        ),
    ]
