# Generated by Django 6.0 on 2025-12-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='peppi_addressing',
            field=models.CharField(choices=[('BY_NAME', 'By Name'), ('CULTURAL', 'Cultural (Bhaiya/Didi)')], default='BY_NAME', help_text='How Peppi addresses the child', max_length=20),
        ),
        migrations.AddField(
            model_name='child',
            name='peppi_gender',
            field=models.CharField(choices=[('MALE', 'Male (Peppi Bhaiya)'), ('FEMALE', 'Female (Peppi Didi)')], default='FEMALE', help_text='Peppi voice gender preference', max_length=10),
        ),
    ]
