# Generated by Django 6.0 on 2025-12-19 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_child_peppi_addressing_child_peppi_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
