# Generated by Django 6.0 on 2025-12-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0004_alter_child_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='language',
            field=models.CharField(choices=[('FIJI_HINDI', 'Fiji Hindi'), ('GUJARATI', 'Gujarati'), ('HINDI', 'Hindi'), ('MALAYALAM', 'Malayalam'), ('PUNJABI', 'Punjabi'), ('TAMIL', 'Tamil'), ('TELUGU', 'Telugu')], default='HINDI', max_length=20),
        ),
    ]
