# Generated by Django 5.2.9 on 2025-12-29 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0006_add_streak_tracking'),
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='family.family'),
        ),
    ]
