# Generated by Django 5.2.9 on 2026-01-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("children", "0007_child_family"),
    ]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="peppi_addressing",
            field=models.CharField(
                choices=[("BY_NAME", "By Name"), ("CULTURAL", "Cultural (Yaar/Dost)")],
                default="BY_NAME",
                help_text="How Peppi addresses the child (friend terms, not elder sibling)",
                max_length=20,
            ),
        ),
    ]
