# Generated by Django 5.2.9 on 2025-12-09 06:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('stories_started', models.IntegerField(default=0)),
                ('stories_completed', models.IntegerField(default=0)),
                ('pages_read', models.IntegerField(default=0)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('points_earned', models.IntegerField(default=0)),
                ('recordings_made', models.IntegerField(default=0)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to='children.child')),
            ],
            options={
                'db_table': 'daily_activities',
                'unique_together': {('child', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20)),
                ('current_page', models.IntegerField(default=0)),
                ('pages_completed', models.IntegerField(default=0)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('points_earned', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='children.child')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='stories.story')),
            ],
            options={
                'db_table': 'progress',
                'unique_together': {('child', 'story')},
            },
        ),
    ]
