# Generated by Django 6.0 on 2025-12-22 00:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0004_alter_child_level'),
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('LESSON_STARTED', 'Lesson Started'), ('LESSON_COMPLETED', 'Lesson Completed'), ('EXERCISE_COMPLETED', 'Exercise Completed'), ('GAME_COMPLETED', 'Game Completed'), ('BADGE_EARNED', 'Badge Earned'), ('LEVEL_UP', 'Level Up'), ('STREAK_MILESTONE', 'Streak Milestone'), ('FIRST_LOGIN', 'First Login')], max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('points_earned', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='children.child')),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['child', '-created_at'], name='activity_lo_child_i_c4e06e_idx'), models.Index(fields=['activity_type'], name='activity_lo_activit_fd7ee5_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('time_spent_minutes', models.IntegerField(default=0)),
                ('lessons_completed', models.IntegerField(default=0)),
                ('exercises_completed', models.IntegerField(default=0)),
                ('games_played', models.IntegerField(default=0)),
                ('points_earned', models.IntegerField(default=0)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to='children.child')),
            ],
            options={
                'db_table': 'daily_progress',
                'ordering': ['-date'],
                'unique_together': {('child', 'date')},
            },
        ),
    ]
