# Generated by Django 6.0 on 2025-12-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the current subscription expires (null = never for free tier)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_tier',
            field=models.CharField(choices=[('FREE', 'Free'), ('STANDARD', 'Standard ($12/month)'), ('PREMIUM', 'Premium ($20/month)')], default='FREE', help_text='User subscription tier determines TTS provider and content access', max_length=20),
        ),
    ]
