# Generated by Django 6.0 on 2025-12-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_subscription_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_tier',
            field=models.CharField(choices=[('FREE', 'Free'), ('STANDARD', 'Standard (NZD $20/month)'), ('PREMIUM', 'Premium (NZD $30/month)')], default='FREE', help_text='User subscription tier determines TTS provider and content access', max_length=20),
        ),
    ]
