# Generated by Django 6.0 on 2026-01-26 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0007_add_live_class_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Organization/tenant this user belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.tenant'),
        ),
    ]
