# Generated by Django 5.2.9 on 2025-12-09 06:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storyweaver_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('title_translit', models.CharField(blank=True, max_length=500, null=True)),
                ('language', models.CharField(choices=[('HINDI', 'Hindi'), ('TAMIL', 'Tamil'), ('GUJARATI', 'Gujarati'), ('PUNJABI', 'Punjabi'), ('TELUGU', 'Telugu'), ('MALAYALAM', 'Malayalam')], max_length=20)),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('page_count', models.IntegerField()),
                ('cover_image_url', models.URLField()),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('illustrator', models.CharField(blank=True, max_length=255, null=True)),
                ('categories', models.JSONField(default=list)),
                ('cached_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'stories',
                'db_table': 'stories',
                'indexes': [models.Index(fields=['language', 'level'], name='stories_languag_7a3d65_idx'), models.Index(fields=['storyweaver_id'], name='stories_storywe_b78465_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoryPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_number', models.IntegerField()),
                ('text_content', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='stories.story')),
            ],
            options={
                'db_table': 'story_pages',
                'ordering': ['page_number'],
                'unique_together': {('story', 'page_number')},
            },
        ),
    ]
