# Generated by Django 6.0 on 2025-12-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='age_max',
            field=models.PositiveIntegerField(default=14, help_text='Maximum age'),
        ),
        migrations.AddField(
            model_name='story',
            name='age_min',
            field=models.PositiveIntegerField(default=4, help_text='Minimum age'),
        ),
        migrations.AddField(
            model_name='story',
            name='is_l1_content',
            field=models.BooleanField(default=False, help_text='Part of L1 curriculum'),
        ),
        migrations.AddField(
            model_name='story',
            name='theme',
            field=models.CharField(blank=True, help_text='Story theme', max_length=100),
        ),
        migrations.AddField(
            model_name='story',
            name='title_hindi',
            field=models.CharField(blank=True, help_text='Hindi title', max_length=500),
        ),
        migrations.AddField(
            model_name='story',
            name='title_romanized',
            field=models.CharField(blank=True, help_text='Romanized title', max_length=500),
        ),
        migrations.AddField(
            model_name='storypage',
            name='text_hindi',
            field=models.TextField(blank=True, help_text='Hindi text'),
        ),
        migrations.AddField(
            model_name='storypage',
            name='text_romanized',
            field=models.TextField(blank=True, help_text='Romanized text'),
        ),
    ]
