# Generated by Django 6.0 on 2025-12-21 10:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_story_age_max_story_age_min_story_is_l1_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='estimated_minutes',
            field=models.PositiveIntegerField(default=3, help_text='Estimated reading time'),
        ),
        migrations.AddField(
            model_name='story',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Story is active'),
        ),
        migrations.AddField(
            model_name='story',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured on homepage'),
        ),
        migrations.AddField(
            model_name='story',
            name='moral_english',
            field=models.TextField(blank=True, help_text='Moral of story in English'),
        ),
        migrations.AddField(
            model_name='story',
            name='moral_hindi',
            field=models.TextField(blank=True, help_text='Moral of story in Hindi'),
        ),
        migrations.AddField(
            model_name='story',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='story',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Display order'),
        ),
        migrations.AddField(
            model_name='story',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('standard', 'Standard'), ('premium', 'Premium')], default='free', help_text='Subscription tier', max_length=20),
        ),
        migrations.AddField(
            model_name='story',
            name='xp_reward',
            field=models.PositiveIntegerField(default=10, help_text='XP reward for completing story'),
        ),
        migrations.AddField(
            model_name='storypage',
            name='highlight_words',
            field=models.JSONField(blank=True, default=list, help_text='Words to highlight for learning'),
        ),
        migrations.AddField(
            model_name='storypage',
            name='image_description',
            field=models.TextField(blank=True, help_text='Description for AI image generation'),
        ),
        migrations.AlterField(
            model_name='story',
            name='cover_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='StoryVocabulary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('word_hindi', models.CharField(max_length=100)),
                ('word_transliteration', models.CharField(max_length=100)),
                ('word_english', models.CharField(max_length=100)),
                ('example_hindi', models.TextField(blank=True)),
                ('example_english', models.TextField(blank=True)),
                ('audio_url', models.CharField(blank=True, max_length=500)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary', to='stories.story')),
            ],
            options={
                'db_table': 'story_vocabulary',
                'ordering': ['story', 'word_hindi'],
            },
        ),
    ]
