# Generated by Django 6.0 on 2025-12-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_add_tier_and_vocabulary_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='language',
            field=models.CharField(choices=[('FIJI_HINDI', 'Fiji Hindi'), ('GUJARATI', 'Gujarati'), ('HINDI', 'Hindi'), ('MALAYALAM', 'Malayalam'), ('PUNJABI', 'Punjabi'), ('TAMIL', 'Tamil'), ('TELUGU', 'Telugu')], max_length=20),
        ),
    ]
