databases:
  - name: bhashamitra-db
    databaseName: bhashamitra
    user: bhashamitra
    plan: free
    region: oregon

services:
  - type: web
    name: bhashamitra-api
    runtime: python
    plan: free
    region: oregon
    rootDir: bhashamitra-backend
    buildCommand: "./build.sh"
    preDeployCommand: "python manage.py migrate && python manage.py seed_badges && python manage.py seed_mimic_challenges && python manage.py seed_test_users || true"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_ENV
        value: prod
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://bhashamitra-frontend.vercel.app,https://bhashamitra-frontend-cjiyfxc3f-trishank-dattas-projects.vercel.app"
      - key: DATABASE_URL
        fromDatabase:
          name: bhashamitra-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.11.4"
