# Generated by Django 6.0 on 2025-12-18 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0003_child_peppi_addressing_child_peppi_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('family_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('discount_tier', models.IntegerField(default=0, help_text='Discount percentage based on family size')),
                ('total_children', models.IntegerField(default=0)),
                ('collective_points', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families_created', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='families', to=settings.AUTH_USER_MODEL)),
                ('primary_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Families',
                'db_table': 'families',
            },
        ),
        migrations.CreateModel(
            name='FamilyLeaderboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_start', models.DateField()),
                ('total_points', models.IntegerField(default=0)),
                ('total_time_minutes', models.IntegerField(default=0)),
                ('stories_completed', models.IntegerField(default=0)),
                ('child_rankings', models.JSONField(default=list, help_text='Ordered list of children by points')),
                ('rank', models.IntegerField(default=0, help_text='Global rank among families')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='family.family')),
            ],
            options={
                'db_table': 'family_leaderboards',
                'indexes': [models.Index(fields=['week_start', 'total_points'], name='family_lead_week_st_5c5ad6_idx')],
                'unique_together': {('family', 'week_start')},
            },
        ),
        migrations.CreateModel(
            name='SiblingChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('challenge_type', models.CharField(choices=[('POINTS', 'Most Points'), ('STORIES', 'Most Stories Read'), ('TIME', 'Most Learning Time'), ('STREAK', 'Longest Streak'), ('WORDS', 'Most Words Learned')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('target_value', models.IntegerField(default=0, help_text='Target to reach or compare against')),
                ('participant_progress', models.JSONField(default=dict, help_text='Progress per participant {child_id: value}')),
                ('prize_description', models.CharField(blank=True, max_length=200)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sibling_challenges', to='family.family')),
                ('participants', models.ManyToManyField(related_name='sibling_challenges', to='children.child')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges_won', to='children.child')),
            ],
            options={
                'db_table': 'sibling_challenges',
                'indexes': [models.Index(fields=['family', 'status'], name='sibling_cha_family__0717a5_idx'), models.Index(fields=['start_date', 'end_date'], name='sibling_cha_start_d_d0d530_idx')],
            },
        ),
    ]
