# Generated by Django 5.2.9 on 2025-12-29 08:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0007_child_family'),
        ('family', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='family_code',
        ),
        migrations.AddField(
            model_name='family',
            name='invite_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='family',
            name='invite_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='discount_tier',
            field=models.IntegerField(default=0, help_text='Discount percentage based on number of children'),
        ),
        migrations.AlterField(
            model_name='siblingchallenge',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sibling_challenges_won', to='children.child'),
        ),
        migrations.CreateModel(
            name='CurriculumChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('challenge_type', models.CharField(choices=[('ALPHABET', 'Alphabet Recognition'), ('VOCABULARY', 'Vocabulary'), ('SENTENCES', 'Sentence Building'), ('MIMIC_PRONUNCIATION', 'Pronunciation Practice'), ('DICTATION', 'Dictation Game')], max_length=30)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='EASY', max_length=10)),
                ('min_level', models.IntegerField(default=1, help_text='Minimum curriculum level (1-10)')),
                ('max_level', models.IntegerField(default=2, help_text='Maximum curriculum level (1-10)')),
                ('custom_words', models.JSONField(blank=True, default=list, help_text='List of custom words for pronunciation/dictation challenges')),
                ('target_count', models.IntegerField(default=10, help_text='Number of items to complete (questions/words)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_challenges', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_challenges', to='family.family')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculum_challenges_won', to='children.child')),
            ],
            options={
                'db_table': 'curriculum_challenges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumChallengeParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_count', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('accuracy_score', models.FloatField(default=0.0, help_text='Percentage correct (0-100)')),
                ('best_accuracy', models.FloatField(default=0.0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='family.curriculumchallenge')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_participations', to='children.child')),
            ],
            options={
                'db_table': 'curriculum_challenge_participants',
            },
        ),
        migrations.CreateModel(
            name='CurriculumChallengeAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(choices=[('ALPHABET', 'Alphabet'), ('VOCABULARY', 'Vocabulary'), ('SENTENCE', 'Sentence'), ('PRONUNCIATION', 'Pronunciation'), ('DICTATION', 'Dictation')], max_length=20)),
                ('item_id', models.CharField(help_text='ID or text of the item', max_length=100)),
                ('item_value', models.TextField(help_text='The actual content (word, letter, etc.)')),
                ('user_answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('transcription', models.TextField(blank=True, help_text='What child said (for dictation)')),
                ('accuracy_score', models.FloatField(default=0.0, help_text='Pronunciation accuracy (0-100)')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='family.curriculumchallengeparticipant')),
            ],
            options={
                'db_table': 'curriculum_challenge_attempts',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('MEMBER', 'Member'), ('OWNER', 'Owner')], default='MEMBER', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_memberships', to='children.child')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='family.family')),
            ],
            options={
                'db_table': 'family_memberships',
            },
        ),
        migrations.AddIndex(
            model_name='curriculumchallenge',
            index=models.Index(fields=['family', 'status'], name='curriculum__family__e7a72a_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculumchallenge',
            index=models.Index(fields=['family', 'challenge_type'], name='curriculum__family__ea2b7b_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculumchallenge',
            index=models.Index(fields=['start_date', 'end_date'], name='curriculum__start_d_5a7aeb_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculumchallengeparticipant',
            index=models.Index(fields=['challenge', 'child'], name='curriculum__challen_6b3339_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculumchallengeparticipant',
            index=models.Index(fields=['challenge', 'accuracy_score'], name='curriculum__challen_710f2e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='curriculumchallengeparticipant',
            unique_together={('challenge', 'child')},
        ),
        migrations.AddIndex(
            model_name='curriculumchallengeattempt',
            index=models.Index(fields=['participant', 'created_at'], name='curriculum__partici_9a4e4b_idx'),
        ),
        migrations.AddIndex(
            model_name='familymembership',
            index=models.Index(fields=['family', 'is_active'], name='family_memb_family__ab7b7c_idx'),
        ),
        migrations.AddIndex(
            model_name='familymembership',
            index=models.Index(fields=['child', 'is_active'], name='family_memb_child_i_7467c1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='familymembership',
            unique_together={('family', 'child')},
        ),
    ]
