# Generated by Django 6.0 on 2025-12-21 12:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0004_alter_child_level'),
        ('curriculum', '0005_peppiphrase'),
        ('festivals', '0002_festivalactivity_festivalprogress_festival_image_url_and_more'),
        ('stories', '0003_add_tier_and_vocabulary_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeppiConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('FESTIVAL_STORY', 'Festival Story'), ('CURRICULUM_HELP', 'Curriculum Help'), ('GENERAL', 'General')], default='GENERAL', help_text='The conversation mode', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the conversation is still active')),
                ('messages_count', models.PositiveIntegerField(default=0, help_text='Total messages in this conversation')),
                ('total_tokens_used', models.PositiveIntegerField(default=0, help_text='Total tokens consumed by this conversation')),
                ('language', models.CharField(default='HINDI', help_text='Primary language for this conversation', max_length=20)),
                ('context_snapshot', models.JSONField(blank=True, default=dict, help_text='Serialized context for conversation resumption')),
                ('last_message_at', models.DateTimeField(auto_now=True, help_text='When the last message was sent')),
                ('ended_at', models.DateTimeField(blank=True, help_text='When the conversation was ended', null=True)),
                ('child', models.ForeignKey(help_text='The child participating in this conversation', on_delete=django.db.models.deletion.CASCADE, related_name='peppi_conversations', to='children.child')),
                ('festival', models.ForeignKey(blank=True, help_text='Festival for FESTIVAL_STORY mode', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peppi_conversations', to='festivals.festival')),
                ('lesson', models.ForeignKey(blank=True, help_text='Lesson for CURRICULUM_HELP mode', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peppi_conversations', to='curriculum.lesson')),
                ('story', models.ForeignKey(blank=True, help_text='Story being narrated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peppi_conversations', to='stories.story')),
            ],
            options={
                'db_table': 'peppi_conversations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PeppiChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], help_text='Who sent this message', max_length=10)),
                ('content_primary', models.TextField(help_text='Primary language content (e.g., Hindi)')),
                ('content_romanized', models.TextField(blank=True, help_text='Romanized version of the content')),
                ('content_english', models.TextField(blank=True, help_text='English translation/version')),
                ('audio_input_url', models.URLField(blank=True, help_text='URL of the user voice recording (for voice input)')),
                ('audio_output_url', models.URLField(blank=True, help_text='URL of Peppi TTS response audio')),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('voice', 'Voice')], default='text', help_text='How the message was input', max_length=10)),
                ('token_count', models.PositiveIntegerField(default=0, help_text='Token count for this message')),
                ('latency_ms', models.PositiveIntegerField(default=0, help_text='Response latency in milliseconds')),
                ('was_moderated', models.BooleanField(default=False, help_text='Whether this message was modified by moderation')),
                ('original_content', models.TextField(blank=True, help_text='Original content before moderation (if moderated)')),
                ('conversation', models.ForeignKey(help_text='The conversation this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='peppi_chat.peppiconversation')),
            ],
            options={
                'db_table': 'peppi_chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PeppiSafetyLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('BLOCKED', 'Blocked'), ('MODIFIED', 'Modified'), ('FLAGGED', 'Flagged'), ('ALLOWED', 'Allowed')], help_text='What action was taken', max_length=20)),
                ('input_content', models.TextField(help_text='The original input content')),
                ('output_content', models.TextField(blank=True, help_text='The modified output (if applicable)')),
                ('reason', models.TextField(help_text='Reason for the moderation action')),
                ('matched_patterns', models.JSONField(blank=True, default=list, help_text='List of patterns that triggered moderation')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', help_text='Severity level of the content', max_length=10)),
                ('reviewed', models.BooleanField(default=False, help_text='Whether this has been reviewed by admin')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When it was reviewed', null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Notes from the review')),
                ('child', models.ForeignKey(help_text='The child involved', on_delete=django.db.models.deletion.CASCADE, related_name='peppi_safety_logs', to='children.child')),
                ('conversation', models.ForeignKey(blank=True, help_text='The conversation where this occurred', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_logs', to='peppi_chat.peppiconversation')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_safety_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'peppi_safety_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PeppiChatUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='The date of usage')),
                ('messages_sent', models.PositiveIntegerField(default=0, help_text='Messages sent today')),
                ('conversations_started', models.PositiveIntegerField(default=0, help_text='Conversations started today')),
                ('voice_messages_sent', models.PositiveIntegerField(default=0, help_text='Voice messages sent today')),
                ('tokens_used', models.PositiveIntegerField(default=0, help_text='Total tokens used today')),
                ('child', models.ForeignKey(help_text='The child', on_delete=django.db.models.deletion.CASCADE, related_name='peppi_chat_usage', to='children.child')),
            ],
            options={
                'db_table': 'peppi_chat_usage',
                'indexes': [models.Index(fields=['child', 'date'], name='peppi_chat__child_i_a87ea6_idx')],
                'unique_together': {('child', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='peppiconversation',
            index=models.Index(fields=['child', 'is_active'], name='peppi_conve_child_i_8edcc9_idx'),
        ),
        migrations.AddIndex(
            model_name='peppiconversation',
            index=models.Index(fields=['mode'], name='peppi_conve_mode_30ccdf_idx'),
        ),
        migrations.AddIndex(
            model_name='peppiconversation',
            index=models.Index(fields=['created_at'], name='peppi_conve_created_45b00d_idx'),
        ),
        migrations.AddIndex(
            model_name='peppichatmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='peppi_chat__convers_51c09c_idx'),
        ),
        migrations.AddIndex(
            model_name='peppichatmessage',
            index=models.Index(fields=['role'], name='peppi_chat__role_c293fa_idx'),
        ),
        migrations.AddIndex(
            model_name='peppisafetylog',
            index=models.Index(fields=['child', 'created_at'], name='peppi_safet_child_i_d1f682_idx'),
        ),
        migrations.AddIndex(
            model_name='peppisafetylog',
            index=models.Index(fields=['action'], name='peppi_safet_action_0d0303_idx'),
        ),
        migrations.AddIndex(
            model_name='peppisafetylog',
            index=models.Index(fields=['severity'], name='peppi_safet_severit_c3076f_idx'),
        ),
        migrations.AddIndex(
            model_name='peppisafetylog',
            index=models.Index(fields=['reviewed'], name='peppi_safet_reviewe_c79821_idx'),
        ),
    ]
