# Generated by Django 6.0 on 2025-12-22 03:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0004_alter_child_level'),
        ('peppi_chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeppiEscalationReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_description', models.TextField(help_text='User description of the issue/error')),
                ('mode', models.CharField(choices=[('FESTIVAL_STORY', 'Festival Story'), ('CURRICULUM_HELP', 'Curriculum Help'), ('GENERAL', 'General')], help_text='The chat mode when escalation occurred', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='PENDING', help_text='Current status of the escalation', max_length=20)),
                ('admin_response', models.TextField(blank=True, help_text='Response from the tech team')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the escalation was resolved', null=True)),
                ('child', models.ForeignKey(help_text='The child who needed help', on_delete=django.db.models.deletion.CASCADE, related_name='peppi_escalation_reports', to='children.child')),
                ('conversation', models.ForeignKey(help_text='The conversation where escalation was needed', on_delete=django.db.models.deletion.CASCADE, related_name='escalation_reports', to='peppi_chat.peppiconversation')),
                ('message', models.ForeignKey(blank=True, help_text='The message that triggered escalation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_reports', to='peppi_chat.peppichatmessage')),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Admin who resolved this', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_escalations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'peppi_escalation_reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['child', 'created_at'], name='peppi_escal_child_i_9fc777_idx'), models.Index(fields=['status'], name='peppi_escal_status_0a36ab_idx'), models.Index(fields=['conversation'], name='peppi_escal_convers_26b3ec_idx')],
            },
        ),
    ]
