# Generated by Django 6.0 on 2025-12-18 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0003_child_peppi_addressing_child_peppi_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentChildActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('activity_type', models.CharField(choices=[('READ_TOGETHER', 'Read Together'), ('PRACTICE_LETTERS', 'Practice Letters'), ('CULTURAL_CRAFT', 'Cultural Craft'), ('COOKING_ACTIVITY', 'Cooking Activity'), ('FESTIVAL_ACTIVITY', 'Festival Activity')], max_length=30)),
                ('description', models.TextField()),
                ('language', models.CharField(max_length=20)),
                ('min_age', models.IntegerField(default=2)),
                ('max_age', models.IntegerField(default=18)),
                ('duration_minutes', models.IntegerField(default=15)),
                ('materials_needed', models.JSONField(default=list)),
                ('learning_outcomes', models.JSONField(default=list)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Parent-child activities',
                'db_table': 'parent_child_activities',
                'indexes': [models.Index(fields=['language', 'activity_type'], name='parent_chil_languag_b93d3b_idx'), models.Index(fields=['min_age', 'max_age'], name='parent_chil_min_age_9ffadd_idx')],
            },
        ),
        migrations.CreateModel(
            name='ParentPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('NONE', 'None')], default='WEEKLY', max_length=20)),
                ('email_reports', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('sms_alerts', models.BooleanField(default=False)),
                ('preferred_report_day', models.IntegerField(default=0, help_text='Day of week for reports (0=Monday, 6=Sunday)')),
                ('timezone', models.CharField(default='Pacific/Auckland', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Parent preferences',
                'db_table': 'parent_preferences',
            },
        ),
        migrations.CreateModel(
            name='LearningGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal_type', models.CharField(choices=[('DAILY_MINUTES', 'Daily Screen Time'), ('WEEKLY_STORIES', 'Stories per Week'), ('MONTHLY_POINTS', 'Points per Month'), ('LEVEL_TARGET', 'Level Target')], max_length=30)),
                ('target_value', models.IntegerField()),
                ('current_value', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_goals', to='children.child')),
            ],
            options={
                'db_table': 'learning_goals',
                'indexes': [models.Index(fields=['child', 'is_active'], name='learning_go_child_i_cbf14b_idx'), models.Index(fields=['goal_type'], name='learning_go_goal_ty_7fe2a8_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('total_time_minutes', models.IntegerField(default=0)),
                ('stories_completed', models.IntegerField(default=0)),
                ('points_earned', models.IntegerField(default=0)),
                ('new_words_learned', models.IntegerField(default=0)),
                ('achievements_unlocked', models.JSONField(default=list)),
                ('areas_of_strength', models.JSONField(default=list)),
                ('areas_for_improvement', models.JSONField(default=list)),
                ('peppi_interactions', models.IntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='children.child')),
            ],
            options={
                'db_table': 'weekly_reports',
                'indexes': [models.Index(fields=['child', 'week_start'], name='weekly_repo_child_i_fcbc24_idx')],
                'unique_together': {('child', 'week_start')},
            },
        ),
    ]
