# Generated by Django 6.0 on 2025-12-27 23:28

import apps.challenges.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0006_add_streak_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, default=apps.challenges.models.generate_challenge_code, max_length=10, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('title_native', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(choices=[('HINDI', 'Hindi'), ('TAMIL', 'Tamil'), ('GUJARATI', 'Gujarati'), ('PUNJABI', 'Punjabi'), ('TELUGU', 'Telugu'), ('MALAYALAM', 'Malayalam'), ('FIJI_HINDI', 'Fiji Hindi')], max_length=20)),
                ('category', models.CharField(choices=[('alphabet', 'Alphabet Recognition'), ('vocabulary', 'Vocabulary'), ('numbers', 'Numbers & Counting'), ('colors', 'Colors'), ('animals', 'Animals'), ('family', 'Family Members'), ('food', 'Food & Fruits'), ('greetings', 'Greetings & Phrases')], default='vocabulary', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy (Ages 4-6)'), ('medium', 'Medium (Ages 7-10)'), ('hard', 'Hard (Ages 11-14)')], default='easy', max_length=10)),
                ('question_count', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(10)])),
                ('time_limit_seconds', models.PositiveIntegerField(default=30)),
                ('questions', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('total_completions', models.PositiveIntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_challenges', to=settings.AUTH_USER_MODEL)),
                ('creator_child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='children.child')),
            ],
            options={
                'db_table': 'challenges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant_name', models.CharField(max_length=50)),
                ('participant_location', models.CharField(blank=True, max_length=50)),
                ('score', models.PositiveIntegerField(default=0)),
                ('max_score', models.PositiveIntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('answers', models.JSONField(default=list)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='challenges.challenge')),
                ('participant_child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenge_attempts', to='children.child')),
                ('participant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenge_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'challenge_attempts',
                'ordering': ['-percentage', 'time_taken_seconds'],
            },
        ),
        migrations.CreateModel(
            name='UserChallengeQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenges_created_today', models.PositiveIntegerField(default=0)),
                ('last_reset_date', models.DateField(auto_now_add=True)),
                ('total_challenges_created', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_quota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_challenge_quotas',
            },
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['code'], name='challenges_code_7389d7_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['creator', 'created_at'], name='challenges_creator_a569cf_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['language', 'category'], name='challenges_languag_c00f27_idx'),
        ),
        migrations.AddIndex(
            model_name='challengeattempt',
            index=models.Index(fields=['challenge', 'is_completed'], name='challenge_a_challen_d39db4_idx'),
        ),
        migrations.AddIndex(
            model_name='challengeattempt',
            index=models.Index(fields=['challenge', 'percentage', 'time_taken_seconds'], name='challenge_a_challen_578e93_idx'),
        ),
    ]
