# Generated by Django 5.2.9 on 2026-01-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0002_alter_challenge_creator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="category",
            field=models.CharField(
                choices=[
                    ("alphabet", "Alphabet Recognition"),
                    ("vocabulary", "Vocabulary"),
                    ("numbers", "Numbers & Counting"),
                    ("colors", "Colors"),
                    ("animals", "Animals"),
                    ("family", "Family Members"),
                    ("food", "Food & Fruits"),
                    ("greetings", "Greetings & Phrases"),
                    ("mimic", "Mimic the Sentence"),
                ],
                default="vocabulary",
                max_length=20,
            ),
        ),
    ]
