# Generated by Django 5.2.9 on 2026-01-24 01:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0003_alter_challenge_category"),
        ("children", "0008_alter_child_peppi_addressing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="category",
            field=models.CharField(
                choices=[
                    ("alphabet", "Alphabet Recognition"),
                    ("vocabulary", "Vocabulary"),
                    ("numbers", "Numbers & Counting"),
                    ("colors", "Colors"),
                    ("animals", "Animals"),
                    ("family", "Family Members"),
                    ("food", "Food & Fruits"),
                    ("greetings", "Greetings & Phrases"),
                    ("grammar", "Grammar"),
                ],
                default="vocabulary",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PlayerRating",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("current_rating", models.IntegerField(default=1000)),
                ("highest_rating", models.IntegerField(default=1000)),
                ("lowest_rating", models.IntegerField(default=1000)),
                ("total_matches", models.IntegerField(default=0)),
                ("wins", models.IntegerField(default=0)),
                ("losses", models.IntegerField(default=0)),
                ("draws", models.IntegerField(default=0)),
                ("current_win_streak", models.IntegerField(default=0)),
                ("best_win_streak", models.IntegerField(default=0)),
                ("current_loss_streak", models.IntegerField(default=0)),
                ("underdog_wins", models.IntegerField(default=0)),
                ("giant_slayer_wins", models.IntegerField(default=0)),
                ("rank_title", models.CharField(default="Learner", max_length=50)),
                (
                    "child",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_rating",
                        to="children.child",
                    ),
                ),
            ],
            options={
                "db_table": "player_ratings",
                "ordering": ["-current_rating"],
            },
        ),
        migrations.CreateModel(
            name="RatingHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rating_before", models.IntegerField()),
                ("rating_after", models.IntegerField()),
                ("rating_change", models.IntegerField()),
                ("opponent_rating", models.IntegerField(blank=True, null=True)),
                ("is_win", models.BooleanField()),
                (
                    "challenge_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating_changes",
                        to="challenges.challengeattempt",
                    ),
                ),
                (
                    "player_rating",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="challenges.playerrating",
                    ),
                ),
            ],
            options={
                "db_table": "rating_history",
                "ordering": ["-created_at"],
            },
        ),
    ]
