# Generated by Django 6.0 on 2025-12-19 10:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0004_alter_child_level'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumLevel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Level code (L1, L2, etc.)', max_length=5, unique=True)),
                ('name_english', models.CharField(help_text='English name', max_length=50)),
                ('name_hindi', models.CharField(help_text='Hindi name', max_length=50)),
                ('name_romanized', models.CharField(help_text='Romanized Hindi name', max_length=50)),
                ('min_age', models.PositiveSmallIntegerField(help_text='Minimum age for this level')),
                ('max_age', models.PositiveSmallIntegerField(help_text='Maximum age for this level')),
                ('description', models.TextField(help_text='Level description and goals')),
                ('learning_objectives', models.JSONField(default=list, help_text='List of learning objectives')),
                ('peppi_welcome', models.TextField(blank=True, help_text='Peppi welcome message for level')),
                ('peppi_completion', models.TextField(blank=True, help_text='Peppi completion message')),
                ('emoji', models.CharField(help_text='Emoji representing the level', max_length=10)),
                ('theme_color', models.CharField(default='#6366f1', help_text='Hex color code', max_length=7)),
                ('order', models.PositiveSmallIntegerField(help_text='Display order', unique=True)),
                ('estimated_hours', models.PositiveSmallIntegerField(default=20, help_text='Estimated hours to complete')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'curriculum_levels',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['code'], name='curriculum__code_226540_idx'), models.Index(fields=['order'], name='curriculum__order_5bc3c6_idx'), models.Index(fields=['is_active'], name='curriculum__is_acti_333d93_idx')],
            },
        ),
        migrations.CreateModel(
            name='CurriculumModule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Module code (L1.M1, L2.M3, etc.)', max_length=20)),
                ('name_english', models.CharField(help_text='English name', max_length=100)),
                ('name_hindi', models.CharField(help_text='Hindi name', max_length=100)),
                ('name_romanized', models.CharField(help_text='Romanized Hindi name', max_length=100)),
                ('module_type', models.CharField(choices=[('LISTENING', 'Listening & Recognition'), ('SPEAKING', 'Speaking & Pronunciation'), ('VOCABULARY', 'Vocabulary Building'), ('ALPHABET', 'Alphabet & Letters'), ('READING', 'Reading Practice'), ('GRAMMAR', 'Grammar Concepts'), ('STORIES', 'Story Time'), ('SONGS', 'Songs & Rhymes'), ('GAMES', 'Games & Activities'), ('CULTURE', 'Cultural Learning')], help_text='Type of learning module', max_length=20)),
                ('description', models.TextField(help_text='Module description and learning goals')),
                ('peppi_intro', models.TextField(blank=True, help_text='Peppi introduction for module')),
                ('peppi_completion', models.TextField(blank=True, help_text='Peppi completion message')),
                ('emoji', models.CharField(help_text='Emoji representing the module', max_length=10)),
                ('order', models.PositiveSmallIntegerField(help_text='Order within level')),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=30, help_text='Estimated minutes to complete')),
                ('is_active', models.BooleanField(default=True)),
                ('level', models.ForeignKey(help_text='Parent curriculum level', on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='curriculum.curriculumlevel')),
            ],
            options={
                'db_table': 'curriculum_modules',
                'ordering': ['level', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Lesson code (L1.M1.LS1, etc.)', max_length=30)),
                ('title_english', models.CharField(help_text='English title', max_length=200)),
                ('title_hindi', models.CharField(help_text='Hindi title', max_length=200)),
                ('title_romanized', models.CharField(help_text='Romanized Hindi title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Lesson description')),
                ('peppi_intro', models.TextField(blank=True, help_text='Peppi introduction for lesson')),
                ('peppi_success', models.TextField(blank=True, help_text='Peppi success message')),
                ('order', models.PositiveSmallIntegerField(help_text='Order within module')),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=10, help_text='Estimated minutes')),
                ('points_available', models.PositiveIntegerField(default=10, help_text='Points available for completion')),
                ('mastery_threshold', models.PositiveSmallIntegerField(default=80, help_text='Percentage required for mastery', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('module', models.ForeignKey(help_text='Parent module', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculum.curriculummodule')),
            ],
            options={
                'db_table': 'curriculum_lessons',
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LessonContent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('VOCABULARY_THEME', 'Vocabulary Theme'), ('VOCABULARY_WORD', 'Vocabulary Word'), ('LETTER', 'Alphabet Letter'), ('GRAMMAR_TOPIC', 'Grammar Topic'), ('GAME', 'Game'), ('STORY', 'Story'), ('ASSESSMENT', 'Assessment')], help_text='Type of content', max_length=30)),
                ('content_id', models.UUIDField(help_text='UUID of the referenced content')),
                ('sequence_order', models.PositiveSmallIntegerField(default=0, help_text='Order in which content appears')),
                ('is_required', models.BooleanField(default=True, help_text='Whether this content is required for lesson completion')),
                ('lesson', models.ForeignKey(help_text='Parent lesson', on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='curriculum.lesson')),
            ],
            options={
                'db_table': 'lesson_contents',
                'ordering': ['lesson', 'sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveSmallIntegerField(default=0, help_text='Latest score percentage')),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='Number of attempts')),
                ('best_score', models.PositiveSmallIntegerField(default=0, help_text='Best score achieved')),
                ('is_complete', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='children.child')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_progress', to='curriculum.lesson')),
            ],
            options={
                'db_table': 'lesson_progress',
            },
        ),
        migrations.CreateModel(
            name='LevelProgress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('modules_completed', models.PositiveSmallIntegerField(default=0)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_progress', to='children.child')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_progress', to='curriculum.curriculumlevel')),
            ],
            options={
                'db_table': 'level_progress',
            },
        ),
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lessons_completed', models.PositiveSmallIntegerField(default=0)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to='children.child')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_progress', to='curriculum.curriculummodule')),
            ],
            options={
                'db_table': 'module_progress',
            },
        ),
        migrations.AddIndex(
            model_name='curriculummodule',
            index=models.Index(fields=['level', 'order'], name='curriculum__level_i_f98af7_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculummodule',
            index=models.Index(fields=['module_type'], name='curriculum__module__aba3c7_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculummodule',
            index=models.Index(fields=['is_active'], name='curriculum__is_acti_d4fdc9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='curriculummodule',
            unique_together={('level', 'code')},
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module', 'order'], name='curriculum__module__71f17f_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['is_active'], name='curriculum__is_acti_d1d672_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('module', 'code')},
        ),
        migrations.AddIndex(
            model_name='lessoncontent',
            index=models.Index(fields=['lesson', 'sequence_order'], name='lesson_cont_lesson__407a51_idx'),
        ),
        migrations.AddIndex(
            model_name='lessoncontent',
            index=models.Index(fields=['content_type', 'content_id'], name='lesson_cont_content_e60a1f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lessoncontent',
            unique_together={('lesson', 'content_type', 'content_id')},
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['child', 'is_complete'], name='lesson_prog_child_i_e0694c_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['lesson'], name='lesson_prog_lesson__568578_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('child', 'lesson')},
        ),
        migrations.AddIndex(
            model_name='levelprogress',
            index=models.Index(fields=['child', 'is_complete'], name='level_progr_child_i_a318be_idx'),
        ),
        migrations.AddIndex(
            model_name='levelprogress',
            index=models.Index(fields=['level'], name='level_progr_level_i_207be5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='levelprogress',
            unique_together={('child', 'level')},
        ),
        migrations.AddIndex(
            model_name='moduleprogress',
            index=models.Index(fields=['child', 'is_complete'], name='module_prog_child_i_438379_idx'),
        ),
        migrations.AddIndex(
            model_name='moduleprogress',
            index=models.Index(fields=['module'], name='module_prog_module__6fc392_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='moduleprogress',
            unique_together={('child', 'module')},
        ),
    ]
