# Generated by Django 6.0 on 2025-12-19 11:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0004_alter_child_level'),
        ('curriculum', '0002_curriculumlevel_curriculummodule_lesson_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeppiPersonality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age_group', models.CharField(help_text='Age group (4-5, 6-8, 9-11, 12-14)', max_length=20, unique=True)),
                ('greeting_style', models.TextField(help_text='How Peppi greets children')),
                ('encouragement_phrases', models.JSONField(default=list, help_text='List of encouragement phrases')),
                ('teaching_style', models.TextField(help_text='Teaching approach description')),
                ('voice_tone', models.CharField(help_text='Voice tone and style', max_length=50)),
                ('avatar_expression', models.CharField(default='happy', help_text='Default avatar expression', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Peppi Personalities',
                'db_table': 'peppi_personalities',
            },
        ),
        migrations.CreateModel(
            name='PeppiLearningContext',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_topic', models.CharField(blank=True, help_text='Current learning topic', max_length=200)),
                ('words_taught_today', models.JSONField(default=list, help_text='Words taught in current session')),
                ('mistakes_made', models.JSONField(default=list, help_text='Recent mistakes for adaptive learning')),
                ('mood', models.CharField(default='neutral', help_text='Current mood assessment', max_length=50)),
                ('last_interaction', models.DateTimeField(auto_now=True, help_text='Last interaction timestamp')),
                ('total_sessions', models.PositiveIntegerField(default=0, help_text='Total learning sessions')),
                ('streak_days', models.PositiveIntegerField(default=0, help_text='Current learning streak')),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='peppi_context', to='children.child')),
            ],
            options={
                'verbose_name_plural': 'Peppi Learning Contexts',
                'db_table': 'peppi_learning_contexts',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_english', models.CharField(help_text='English title', max_length=200)),
                ('title_hindi', models.CharField(help_text='Hindi title', max_length=200)),
                ('title_romanized', models.CharField(help_text='Romanized title', max_length=200)),
                ('lyrics_hindi', models.TextField(help_text='Hindi lyrics')),
                ('lyrics_romanized', models.TextField(help_text='Romanized lyrics')),
                ('lyrics_english', models.TextField(help_text='English translation')),
                ('age_min', models.PositiveIntegerField(default=4, help_text='Minimum age')),
                ('age_max', models.PositiveIntegerField(default=6, help_text='Maximum age')),
                ('duration_seconds', models.PositiveIntegerField(default=60, help_text='Song duration in seconds')),
                ('audio_url', models.URLField(blank=True, help_text='Audio file URL')),
                ('video_url', models.URLField(blank=True, help_text='Video URL')),
                ('category', models.CharField(choices=[('RHYME', 'Nursery Rhyme'), ('FOLK', 'Folk Song'), ('EDUCATIONAL', 'Educational'), ('FESTIVAL', 'Festival Song')], default='RHYME', help_text='Song category', max_length=50)),
                ('actions', models.JSONField(default=list, help_text='Action instructions for the song')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True, help_text='Active status')),
                ('level', models.ForeignKey(help_text='Curriculum level', on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='curriculum.curriculumlevel')),
            ],
            options={
                'db_table': 'curriculum_songs',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['level', 'order'], name='curriculum__level_i_184b0d_idx'), models.Index(fields=['category'], name='curriculum__categor_9b9082_idx'), models.Index(fields=['is_active'], name='curriculum__is_acti_e8812d_idx')],
            },
        ),
    ]
