# Generated by Django 6.0 on 2025-12-19 22:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_peppipersonality_peppilearningcontext_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Teacher name in English', max_length=100)),
                ('name_hindi', models.CharField(help_text='Teacher name in Hindi', max_length=100)),
                ('character_type', models.CharField(choices=[('CAT', 'Ragdoll Cat (Peppi)'), ('OWL', 'Wise Owl (Gyan)')], help_text='Type of character (Cat/Owl)', max_length=20)),
                ('breed', models.CharField(blank=True, help_text='Animal breed', max_length=100)),
                ('personality', models.TextField(help_text='Personality traits and teaching style')),
                ('voice_style', models.CharField(help_text='Voice characteristics', max_length=100)),
                ('avatar_url', models.URLField(blank=True, help_text='URL to avatar image')),
                ('intro_message', models.TextField(blank=True, help_text='Default introduction message')),
                ('encouragement_phrases', models.JSONField(default=list, help_text='List of encouragement phrases')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'curriculum_teachers',
                'ordering': ['character_type', 'name'],
                'indexes': [models.Index(fields=['character_type'], name='curriculum__charact_c25012_idx'), models.Index(fields=['is_active'], name='curriculum__is_acti_7405f2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Classroom name in English', max_length=100)),
                ('name_hindi', models.CharField(help_text='Classroom name in Hindi', max_length=100)),
                ('theme', models.CharField(help_text='Theme identifier', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the classroom')),
                ('elements', models.JSONField(default=list, help_text='Visual elements in the classroom')),
                ('background_color', models.CharField(help_text='Hex color code', max_length=7)),
                ('background_image_url', models.URLField(blank=True, help_text='Background image URL')),
                ('unlock_animation', models.CharField(blank=True, help_text='Animation type', max_length=50)),
                ('ambient_sounds', models.JSONField(default=list, help_text='Ambient sound URLs')),
                ('is_active', models.BooleanField(default=True)),
                ('level', models.OneToOneField(help_text='Associated curriculum level', on_delete=django.db.models.deletion.CASCADE, related_name='classroom', to='curriculum.curriculumlevel')),
            ],
            options={
                'db_table': 'classrooms',
                'ordering': ['level__order'],
                'indexes': [models.Index(fields=['level'], name='classrooms_level_i_59bbae_idx'), models.Index(fields=['is_active'], name='classrooms_is_acti_148ca3_idx')],
            },
        ),
    ]
