# Generated by Django 6.0 on 2025-12-21 04:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_add_teacher_classroom_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeppiPhrase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('correct', 'Correct Answer'), ('wrong', 'Wrong Answer'), ('streak', 'Streak Celebration'), ('greeting', 'Greeting'), ('farewell', 'Farewell'), ('encouragement', 'Encouragement'), ('completion', 'Completion'), ('badge', 'Badge Earned')], help_text='Phrase category', max_length=20)),
                ('text_hindi', models.TextField(help_text='Hindi/Hinglish text')),
                ('text_english', models.TextField(blank=True, help_text='English translation')),
                ('text_romanized', models.TextField(blank=True, help_text='Romanized text')),
                ('audio_file', models.CharField(blank=True, help_text='Audio file path', max_length=255)),
                ('streak_count', models.PositiveIntegerField(blank=True, help_text='Streak count for streak phrases', null=True)),
                ('context', models.CharField(blank=True, help_text='Context (e.g., morning, afternoon, return)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'peppi_phrases',
                'ordering': ['category', 'id'],
                'indexes': [models.Index(fields=['category'], name='peppi_phras_categor_fdcb93_idx'), models.Index(fields=['is_active'], name='peppi_phras_is_acti_298930_idx')],
            },
        ),
    ]
