# Generated by Django 6.0 on 2025-12-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_peppiphrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumlevel',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Available in free tier'),
        ),
        migrations.AddField(
            model_name='curriculumlevel',
            name='min_xp_required',
            field=models.PositiveIntegerField(default=0, help_text='Minimum XP required to unlock this level'),
        ),
        migrations.AddField(
            model_name='curriculumlevel',
            name='xp_reward',
            field=models.PositiveIntegerField(default=100, help_text='XP reward for completing this level'),
        ),
        migrations.AddField(
            model_name='curriculummodule',
            name='objectives',
            field=models.JSONField(blank=True, default=list, help_text='List of learning objectives for this module'),
        ),
        migrations.AddField(
            model_name='curriculummodule',
            name='xp_reward',
            field=models.PositiveIntegerField(default=30, help_text='XP reward for completing this module'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.JSONField(blank=True, default=dict, help_text='Lesson content including sections, exercises, and summary'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Available in free tier'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('INTRODUCTION', 'Introduction'), ('LEARNING', 'Learning'), ('PRACTICE', 'Practice'), ('REVIEW', 'Review'), ('STORY', 'Story Time'), ('ASSESSMENT', 'Assessment')], default='LEARNING', help_text='Type of lesson', max_length=20),
        ),
    ]
