# Generated by Django 6.0 on 2025-12-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_curriculumlevel_is_free_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='language',
            field=models.CharField(choices=[('FIJI_HINDI', 'Fiji Hindi'), ('GUJARATI', 'Gujarati'), ('HINDI', 'Hindi'), ('MALAYALAM', 'Malayalam'), ('PUNJABI', 'Punjabi'), ('TAMIL', 'Tamil'), ('TELUGU', 'Telugu')], max_length=20),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='language',
            field=models.CharField(choices=[('FIJI_HINDI', 'Fiji Hindi'), ('GUJARATI', 'Gujarati'), ('HINDI', 'Hindi'), ('MALAYALAM', 'Malayalam'), ('PUNJABI', 'Punjabi'), ('TAMIL', 'Tamil'), ('TELUGU', 'Telugu')], max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='language',
            field=models.CharField(choices=[('FIJI_HINDI', 'Fiji Hindi'), ('GUJARATI', 'Gujarati'), ('HINDI', 'Hindi'), ('MALAYALAM', 'Malayalam'), ('PUNJABI', 'Punjabi'), ('TAMIL', 'Tamil'), ('TELUGU', 'Telugu')], max_length=20),
        ),
        migrations.AlterField(
            model_name='grammartopic',
            name='language',
            field=models.CharField(choices=[('FIJI_HINDI', 'Fiji Hindi'), ('GUJARATI', 'Gujarati'), ('HINDI', 'Hindi'), ('MALAYALAM', 'Malayalam'), ('PUNJABI', 'Punjabi'), ('TAMIL', 'Tamil'), ('TELUGU', 'Telugu')], max_length=20),
        ),
        migrations.AlterField(
            model_name='script',
            name='language',
            field=models.CharField(choices=[('FIJI_HINDI', 'Fiji Hindi'), ('GUJARATI', 'Gujarati'), ('HINDI', 'Hindi'), ('MALAYALAM', 'Malayalam'), ('PUNJABI', 'Punjabi'), ('TAMIL', 'Tamil'), ('TELUGU', 'Telugu')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='vocabularytheme',
            name='language',
            field=models.CharField(choices=[('FIJI_HINDI', 'Fiji Hindi'), ('GUJARATI', 'Gujarati'), ('HINDI', 'Hindi'), ('MALAYALAM', 'Malayalam'), ('PUNJABI', 'Punjabi'), ('TAMIL', 'Tamil'), ('TELUGU', 'Telugu')], max_length=20),
        ),
    ]
