# Generated by Django 6.0 on 2025-12-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_alter_assessment_language_alter_certificate_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='language',
            field=models.CharField(choices=[('FIJI_HINDI', 'Fiji Hindi'), ('GUJARATI', 'Gujarati'), ('HINDI', 'Hindi'), ('MALAYALAM', 'Malayalam'), ('PUNJABI', 'Punjabi'), ('TAMIL', 'Tamil'), ('TELUGU', 'Telugu')], default='HINDI', help_text='Language of the song', max_length=20),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['language'], name='curriculum__languag_96d61b_idx'),
        ),
    ]
