# Generated by Django 6.0 on 2025-12-26 08:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0008_add_language_to_song'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedLetter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(max_length=20)),
                ('character', models.CharField(max_length=10)),
                ('romanization', models.CharField(max_length=50)),
                ('pronunciation_guide', models.CharField(max_length=200)),
                ('example_word', models.CharField(blank=True, max_length=100)),
                ('example_word_meaning', models.CharField(blank=True, max_length=200)),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('NEEDS_REVISION', 'Needs Revision')], default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('pronunciation_accuracy', models.IntegerField(default=0)),
                ('example_relevance', models.IntegerField(default=0)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verified_letters',
                'ordering': ['language', 'character'],
                'unique_together': {('language', 'character')},
            },
        ),
        migrations.CreateModel(
            name='VerifiedWord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(max_length=20)),
                ('word', models.CharField(max_length=200)),
                ('romanization', models.CharField(max_length=200)),
                ('translation', models.CharField(max_length=200)),
                ('part_of_speech', models.CharField(max_length=50)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('example_sentence', models.TextField(blank=True)),
                ('example_sentence_translation', models.TextField(blank=True)),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('NEEDS_REVISION', 'Needs Revision')], default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('translation_accuracy', models.IntegerField(default=0)),
                ('cultural_appropriateness', models.IntegerField(default=0)),
                ('age_appropriateness', models.IntegerField(default=0)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_words', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verified_words',
                'ordering': ['language', 'word'],
                'unique_together': {('language', 'word')},
            },
        ),
    ]
