# Generated by Django 6.0 on 2025-12-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0009_verifiedletter_verifiedword'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='example_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
