# Generated by Django 6.0 on 2025-12-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0010_add_example_image_to_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifiedletter',
            name='example_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
