# Generated by Django 5.2.9 on 2025-12-09 10:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TTSUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text_length', models.IntegerField()),
                ('language', models.CharField(max_length=20)),
                ('voice_style', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('cached', 'Served from Cache'), ('error', 'Error')], max_length=20)),
                ('was_cached', models.BooleanField(default=False)),
                ('response_time_ms', models.IntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TTS Usage Log',
                'verbose_name_plural': 'TTS Usage Logs',
                'db_table': 'tts_usage_log',
            },
        ),
        migrations.CreateModel(
            name='AudioCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cache_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('text_content', models.TextField(help_text='Original text that was converted to speech')),
                ('text_hash', models.CharField(db_index=True, help_text='MD5 hash of text for lookup', max_length=64)),
                ('language', models.CharField(choices=[('HINDI', 'Hindi'), ('TAMIL', 'Tamil'), ('GUJARATI', 'Gujarati'), ('PUNJABI', 'Punjabi'), ('TELUGU', 'Telugu'), ('MALAYALAM', 'Malayalam')], max_length=20)),
                ('voice_style', models.CharField(choices=[('storyteller', 'Storyteller (Warm & Engaging)'), ('calm', 'Calm (Soft & Soothing)'), ('enthusiastic', 'Enthusiastic (Energetic)')], default='storyteller', max_length=20)),
                ('audio_url', models.URLField(blank=True, help_text='URL to the cached audio file')),
                ('audio_duration_ms', models.IntegerField(default=0, help_text='Duration in milliseconds')),
                ('audio_size_bytes', models.IntegerField(default=0, help_text='File size in bytes')),
                ('audio_format', models.CharField(default='wav', max_length=10)),
                ('access_count', models.IntegerField(default=0, help_text='Number of times this audio was accessed')),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('generation_time_ms', models.IntegerField(default=0, help_text='Time taken to generate in ms')),
                ('generation_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_cache', to='stories.story')),
            ],
            options={
                'verbose_name': 'Audio Cache',
                'verbose_name_plural': 'Audio Cache Entries',
                'db_table': 'audio_cache',
                'indexes': [models.Index(fields=['language', 'voice_style'], name='audio_cache_languag_390ee3_idx'), models.Index(fields=['story', 'page_number'], name='audio_cache_story_i_445773_idx'), models.Index(fields=['text_hash'], name='audio_cache_text_ha_a95af9_idx')],
            },
        ),
    ]
