# Generated by Django 6.0 on 2025-12-13 01:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0001_initial'),
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audiocache',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='audio_cache/'),
        ),
        migrations.AddField(
            model_name='audiocache',
            name='content_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='audiocache',
            name='content_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='audiocache',
            name='provider',
            field=models.CharField(choices=[('cache', 'Pre-generated Cache'), ('replicate', 'Replicate.com'), ('google', 'Google Cloud TTS'), ('svara', 'Svara TTS (Legacy)'), ('mms', 'Facebook MMS')], default='cache', max_length=20),
        ),
        migrations.AddField(
            model_name='audiocache',
            name='sample_rate',
            field=models.IntegerField(default=22050),
        ),
        migrations.AddField(
            model_name='ttsusagelog',
            name='estimated_cost_cents',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ttsusagelog',
            name='provider',
            field=models.CharField(default='cache', max_length=20),
        ),
        migrations.AddField(
            model_name='ttsusagelog',
            name='success',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='audiocache',
            name='language',
            field=models.CharField(choices=[('HINDI', 'Hindi'), ('TAMIL', 'Tamil'), ('GUJARATI', 'Gujarati'), ('PUNJABI', 'Punjabi'), ('TELUGU', 'Telugu'), ('MALAYALAM', 'Malayalam'), ('BENGALI', 'Bengali'), ('KANNADA', 'Kannada')], max_length=20),
        ),
        migrations.AlterField(
            model_name='audiocache',
            name='voice_style',
            field=models.CharField(choices=[('storyteller', 'Storyteller (Warm & Engaging)'), ('calm', 'Calm (Soft & Soothing)'), ('enthusiastic', 'Enthusiastic (Energetic)'), ('kid_friendly', 'Kid Friendly (Default)'), ('default', 'Default')], default='storyteller', max_length=20),
        ),
        migrations.AlterField(
            model_name='ttsusagelog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('cached', 'Served from Cache'), ('error', 'Error')], default='success', max_length=20),
        ),
        migrations.AlterField(
            model_name='ttsusagelog',
            name='voice_style',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.AddIndex(
            model_name='audiocache',
            index=models.Index(fields=['content_type', 'content_id'], name='audio_cache_content_66c17c_idx'),
        ),
        migrations.AddIndex(
            model_name='audiocache',
            index=models.Index(fields=['provider'], name='audio_cache_provide_773cc3_idx'),
        ),
        migrations.AddIndex(
            model_name='ttsusagelog',
            index=models.Index(fields=['created_at'], name='tts_usage_l_created_2fe6e6_idx'),
        ),
        migrations.AddIndex(
            model_name='ttsusagelog',
            index=models.Index(fields=['provider', 'was_cached'], name='tts_usage_l_provide_54c1c0_idx'),
        ),
    ]
