# Generated by Django 6.0 on 2025-12-18 23:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_child_peppi_addressing_child_peppi_gender'),
        ('speech', '0002_add_provider_and_audio_file_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeppiMimicChallenge',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word', models.CharField(help_text='Word in native script', max_length=100)),
                ('romanization', models.CharField(help_text='Transliteration', max_length=100)),
                ('meaning', models.CharField(help_text='English meaning', max_length=200)),
                ('language', models.CharField(choices=[('HINDI', 'Hindi'), ('TAMIL', 'Tamil'), ('GUJARATI', 'Gujarati'), ('PUNJABI', 'Punjabi'), ('TELUGU', 'Telugu'), ('MALAYALAM', 'Malayalam'), ('BENGALI', 'Bengali'), ('KANNADA', 'Kannada')], max_length=20)),
                ('audio_url', models.URLField(blank=True, help_text="Peppi's pronunciation audio URL")),
                ('category', models.CharField(choices=[('GREETING', 'Greetings'), ('FAMILY', 'Family Words'), ('FOOD', 'Food & Drink'), ('NUMBERS', 'Numbers'), ('COLORS', 'Colors'), ('ANIMALS', 'Animals'), ('FESTIVAL', 'Festival Words'), ('DAILY', 'Daily Words'), ('ACTIONS', 'Action Words'), ('BODY', 'Body Parts')], max_length=20)),
                ('difficulty', models.PositiveSmallIntegerField(default=1, help_text='1=Easy, 2=Medium, 3=Hard', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('display_order', models.IntegerField(default=0)),
                ('points_reward', models.PositiveIntegerField(default=25, help_text='Base points for completing')),
                ('peppi_intro', models.TextField(blank=True, help_text="What Peppi says before (e.g., 'Listen carefully!')")),
                ('peppi_perfect', models.TextField(blank=True, help_text="3-star response (e.g., 'PERFECT! You're amazing!')")),
                ('peppi_good', models.TextField(blank=True, help_text="2-star response (e.g., 'Very good! Almost there!')")),
                ('peppi_try_again', models.TextField(blank=True, help_text="1-star or less response (e.g., 'Good try! Let's practice more!')")),
                ('is_active', models.BooleanField(default=True)),
                ('audio_cache', models.ForeignKey(blank=True, help_text='Link to cached audio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mimic_challenges', to='speech.audiocache')),
            ],
            options={
                'db_table': 'peppi_mimic_challenges',
                'ordering': ['category', 'difficulty', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='PeppiMimicAttempt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_url', models.URLField(help_text="Child's recording URL")),
                ('duration_ms', models.PositiveIntegerField(default=0, help_text='Recording duration in ms')),
                ('stt_transcription', models.CharField(blank=True, help_text='What STT heard', max_length=200)),
                ('stt_confidence', models.FloatField(default=0, help_text='STT confidence 0-1', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('text_match_score', models.FloatField(default=0, help_text='Text similarity score 0-100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('final_score', models.FloatField(default=0, help_text='Combined final score 0-100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('stars', models.PositiveSmallIntegerField(default=0, help_text='Star rating 0-3', validators=[django.core.validators.MaxValueValidator(3)])),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('is_personal_best', models.BooleanField(default=False)),
                ('shared_to_family', models.BooleanField(default=False)),
                ('shared_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mimic_attempts', to='children.child')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='speech.peppimimicchallenge')),
            ],
            options={
                'db_table': 'peppi_mimic_attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PeppiMimicProgress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('best_score', models.FloatField(default=0)),
                ('best_stars', models.PositiveSmallIntegerField(default=0)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('mastered', models.BooleanField(default=False, help_text='3 stars achieved')),
                ('mastered_at', models.DateTimeField(blank=True, null=True)),
                ('best_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='speech.peppimimicattempt')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_progress', to='speech.peppimimicchallenge')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mimic_progress', to='children.child')),
            ],
            options={
                'db_table': 'peppi_mimic_progress',
            },
        ),
        migrations.AddIndex(
            model_name='peppimimicchallenge',
            index=models.Index(fields=['language', 'category'], name='peppi_mimic_languag_3c0999_idx'),
        ),
        migrations.AddIndex(
            model_name='peppimimicchallenge',
            index=models.Index(fields=['language', 'difficulty'], name='peppi_mimic_languag_3c14b3_idx'),
        ),
        migrations.AddIndex(
            model_name='peppimimicchallenge',
            index=models.Index(fields=['is_active'], name='peppi_mimic_is_acti_c9fa3a_idx'),
        ),
        migrations.AddConstraint(
            model_name='peppimimicchallenge',
            constraint=models.UniqueConstraint(fields=('word', 'language'), name='unique_word_per_language'),
        ),
        migrations.AddIndex(
            model_name='peppimimicattempt',
            index=models.Index(fields=['child', 'challenge'], name='peppi_mimic_child_i_a44952_idx'),
        ),
        migrations.AddIndex(
            model_name='peppimimicattempt',
            index=models.Index(fields=['child', 'created_at'], name='peppi_mimic_child_i_851073_idx'),
        ),
        migrations.AddIndex(
            model_name='peppimimicattempt',
            index=models.Index(fields=['stars'], name='peppi_mimic_stars_bc7d44_idx'),
        ),
        migrations.AddIndex(
            model_name='peppimimicprogress',
            index=models.Index(fields=['child', 'mastered'], name='peppi_mimic_child_i_14422e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='peppimimicprogress',
            unique_together={('child', 'challenge')},
        ),
    ]
