# Generated by Django 6.0 on 2025-12-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0004_add_acoustic_scoring_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='peppimimicprogress',
            name='current_streak',
            field=models.PositiveIntegerField(default=0, help_text='Current consecutive day streak'),
        ),
        migrations.AddField(
            model_name='peppimimicprogress',
            name='last_attempt_date',
            field=models.DateField(blank=True, help_text='Date of last attempt for streak tracking', null=True),
        ),
        migrations.AddField(
            model_name='peppimimicprogress',
            name='longest_streak',
            field=models.PositiveIntegerField(default=0, help_text='Longest streak achieved'),
        ),
    ]
