# Generated by Django 6.0 on 2025-12-27 07:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0005_add_streak_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiocache',
            name='language',
            field=models.CharField(choices=[('HINDI', 'Hindi'), ('TAMIL', 'Tamil'), ('GUJARATI', 'Gujarati'), ('PUNJABI', 'Punjabi'), ('TELUGU', 'Telugu'), ('MALAYALAM', 'Malayalam'), ('BENGALI', 'Bengali'), ('KANNADA', 'Kannada'), ('MARATHI', 'Marathi'), ('ODIA', 'Odia'), ('ASSAMESE', 'Assamese'), ('URDU', 'Urdu'), ('FIJI_HINDI', 'Fiji Hindi')], max_length=20),
        ),
        migrations.AlterField(
            model_name='peppimimicchallenge',
            name='language',
            field=models.CharField(choices=[('HINDI', 'Hindi'), ('TAMIL', 'Tamil'), ('GUJARATI', 'Gujarati'), ('PUNJABI', 'Punjabi'), ('TELUGU', 'Telugu'), ('MALAYALAM', 'Malayalam'), ('BENGALI', 'Bengali'), ('KANNADA', 'Kannada'), ('MARATHI', 'Marathi'), ('ODIA', 'Odia'), ('ASSAMESE', 'Assamese'), ('URDU', 'Urdu'), ('FIJI_HINDI', 'Fiji Hindi')], max_length=20),
        ),
        migrations.CreateModel(
            name='VoiceCharacter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Character name in English (e.g., 'Peppi', 'Grandmother')", max_length=100)),
                ('name_native', models.CharField(blank=True, help_text="Character name in native script (e.g., 'पेप्पी', 'दादी')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the character and voice style')),
                ('character_type', models.CharField(choices=[('PEPPI', 'Peppi (AI Tutor)'), ('GRANDMOTHER', 'Grandmother'), ('GRANDFATHER', 'Grandfather'), ('TEACHER', 'Teacher'), ('NARRATOR', 'Narrator'), ('PARENT', 'Parent')], help_text='Type of character', max_length=20)),
                ('language', models.CharField(choices=[('HINDI', 'Hindi'), ('TAMIL', 'Tamil'), ('GUJARATI', 'Gujarati'), ('PUNJABI', 'Punjabi'), ('TELUGU', 'Telugu'), ('MALAYALAM', 'Malayalam'), ('BENGALI', 'Bengali'), ('KANNADA', 'Kannada'), ('MARATHI', 'Marathi'), ('ODIA', 'Odia'), ('ASSAMESE', 'Assamese'), ('URDU', 'Urdu'), ('FIJI_HINDI', 'Fiji Hindi')], help_text='Language for this voice character', max_length=20)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NEUTRAL', 'Neutral')], help_text='Voice gender', max_length=10)),
                ('voice_source', models.CharField(choices=[('GOOGLE_TTS', 'Google Cloud TTS'), ('SARVAM_AI', 'Sarvam AI (Indic)'), ('CLONED', 'Cloned Voice (ElevenLabs/Replicate)'), ('CUSTOM', 'Custom Provider')], default='SARVAM_AI', help_text='TTS provider/source for this voice', max_length=20)),
                ('voice_id', models.CharField(blank=True, help_text='External voice ID (e.g., ElevenLabs voice ID, Google voice name, Sarvam speaker)', max_length=200)),
                ('voice_model', models.CharField(blank=True, default='bulbul:v2', help_text="TTS model to use (e.g., 'bulbul:v2' for Sarvam)", max_length=100)),
                ('speaking_rate', models.FloatField(default=0.7, help_text='Speaking rate/pace: 0.5 (slow) to 2.0 (fast), 0.7 is balanced for children', validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(2.0)])),
                ('pitch', models.FloatField(default=0.0, help_text='Voice pitch adjustment: -20 to +20 semitones', validators=[django.core.validators.MinValueValidator(-20.0), django.core.validators.MaxValueValidator(20.0)])),
                ('volume_gain_db', models.FloatField(default=0.0, help_text='Volume gain in decibels: -10 to +10 dB', validators=[django.core.validators.MinValueValidator(-10.0), django.core.validators.MaxValueValidator(10.0)])),
                ('warmth_phrases', models.JSONField(blank=True, default=dict, help_text='JSON object with warmth phrases per language')),
                ('personality_traits', models.JSONField(blank=True, default=dict, help_text='JSON object describing personality traits for AI prompt enhancement')),
                ('is_active', models.BooleanField(default=True, help_text='Is this voice character available for use?')),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default voice for this character type and language?')),
                ('clone_quality_score', models.FloatField(blank=True, help_text='Quality score of cloned voice (0.0 to 1.0)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('clone_sample_count', models.PositiveIntegerField(default=0, help_text='Number of voice samples used for cloning')),
                ('cloned_from_user', models.ForeignKey(blank=True, help_text='User who provided voice samples for cloning (e.g., parent/grandparent)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloned_voices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voice Character',
                'verbose_name_plural': 'Voice Characters',
                'db_table': 'voice_characters',
                'indexes': [models.Index(fields=['character_type', 'language'], name='voice_chara_charact_b8695b_idx'), models.Index(fields=['language', 'is_active'], name='voice_chara_languag_e88b9c_idx'), models.Index(fields=['voice_source'], name='voice_chara_voice_s_a6c958_idx'), models.Index(fields=['is_default'], name='voice_chara_is_defa_39ae7c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('character_type', 'language', 'gender'), name='unique_default_per_character_language_gender')],
            },
        ),
    ]
