# Generated by Django 6.0 on 2025-12-18 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market_code', models.CharField(choices=[('NZ', 'New Zealand'), ('AU', 'Australia'), ('IN', 'India'), ('US', 'United States'), ('UK', 'United Kingdom'), ('CA', 'Canada')], max_length=5, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('currency_code', models.CharField(default='NZD', max_length=3)),
                ('currency_symbol', models.CharField(default='$', max_length=5)),
                ('timezone', models.CharField(default='Pacific/Auckland', max_length=50)),
                ('primary_languages', models.JSONField(default=list)),
                ('pricing_config', models.JSONField(default=dict, help_text='Tier pricing in local currency')),
                ('content_restrictions', models.JSONField(default=dict, help_text='Content availability restrictions')),
                ('legal_config', models.JSONField(default=dict, help_text='Legal requirements (COPPA, GDPR, etc.)')),
                ('payment_methods', models.JSONField(default=list, help_text='Available payment methods')),
                ('is_active', models.BooleanField(default=True)),
                ('launch_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Market Configuration',
                'verbose_name_plural': 'Market Configurations',
                'db_table': 'market_configs',
            },
        ),
        migrations.CreateModel(
            name='FestivalCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('native_name', models.CharField(blank=True, max_length=200)),
                ('festival_type', models.CharField(choices=[('RELIGIOUS', 'Religious'), ('CULTURAL', 'Cultural'), ('NATIONAL', 'National Holiday'), ('SEASONAL', 'Seasonal')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('languages', models.JSONField(default=list, help_text='Languages celebrating this festival')),
                ('markets', models.JSONField(default=list, help_text='Markets where this is observed')),
                ('date_2024', models.DateField(blank=True, null=True)),
                ('date_2025', models.DateField(blank=True, null=True)),
                ('date_2026', models.DateField(blank=True, null=True)),
                ('is_lunar_based', models.BooleanField(default=False)),
                ('content_pack_id', models.UUIDField(blank=True, help_text='Related offline content pack', null=True)),
                ('greeting_translations', models.JSONField(default=dict, help_text='Festival greetings in different languages')),
                ('traditions', models.JSONField(default=list)),
                ('activities', models.JSONField(default=list, help_text='Suggested learning activities')),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'festival_calendars',
                'indexes': [models.Index(fields=['festival_type'], name='festival_ca_festiva_3903da_idx'), models.Index(fields=['date_2025'], name='festival_ca_date_20_e41d47_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegionalContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(max_length=50)),
                ('content_id', models.UUIDField()),
                ('variations', models.JSONField(default=dict, help_text='Market-specific content variations')),
                ('is_available', models.BooleanField(default=True)),
                ('availability_reason', models.CharField(blank=True, max_length=200)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_content', to='localization.marketconfig')),
            ],
            options={
                'db_table': 'regional_content',
                'indexes': [models.Index(fields=['content_type', 'market'], name='regional_co_content_28ea7f_idx')],
                'unique_together': {('content_type', 'content_id', 'market')},
            },
        ),
    ]
