# Generated by Django 6.0 on 2025-12-15 03:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('name_native', models.CharField(help_text='Name in native script', max_length=100)),
                ('religion', models.CharField(choices=[('HINDU', 'Hindu'), ('MUSLIM', 'Muslim'), ('SIKH', 'Sikh'), ('CHRISTIAN', 'Christian'), ('JAIN', 'Jain'), ('BUDDHIST', 'Buddhist')], max_length=20)),
                ('description', models.TextField()),
                ('typical_month', models.IntegerField(help_text='1-12 for typical celebration month')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'festivals',
                'ordering': ['typical_month', 'name'],
                'indexes': [models.Index(fields=['religion'], name='festivals_religio_ebc22f_idx'), models.Index(fields=['typical_month'], name='festivals_typical_89a300_idx')],
            },
        ),
        migrations.CreateModel(
            name='FestivalStory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary story for this festival')),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='festival_stories', to='festivals.festival')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='festival_links', to='stories.story')),
            ],
            options={
                'db_table': 'festival_stories',
                'indexes': [models.Index(fields=['festival', 'is_primary'], name='festival_st_festiva_3abb5f_idx')],
                'unique_together': {('festival', 'story')},
            },
        ),
    ]
