# Generated by Django 6.0 on 2025-12-18 21:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_child_peppi_addressing_child_peppi_gender'),
        ('festivals', '0001_initial'),
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('activity_type', models.CharField(choices=[('STORY', 'Story'), ('CRAFT', 'Craft'), ('COOKING', 'Cooking'), ('SONG', 'Song'), ('GAME', 'Game'), ('VOCABULARY', 'Vocabulary'), ('QUIZ', 'Quiz'), ('VIDEO', 'Video')], help_text='Type of activity', max_length=20)),
                ('description', models.TextField(help_text='Brief description of the activity')),
                ('instructions', models.TextField(help_text='Step-by-step instructions')),
                ('materials_needed', models.JSONField(blank=True, default=list, help_text='List of materials needed for this activity')),
                ('min_age', models.IntegerField(default=3, help_text='Minimum recommended age')),
                ('max_age', models.IntegerField(default=8, help_text='Maximum recommended age')),
                ('duration_minutes', models.IntegerField(default=15, help_text='Estimated duration in minutes')),
                ('difficulty_level', models.IntegerField(default=1, help_text='Difficulty level (1-5)')),
                ('points_reward', models.IntegerField(default=25, help_text='Points awarded on completion')),
                ('image_url', models.URLField(blank=True, help_text='Activity image URL', null=True)),
                ('video_url', models.URLField(blank=True, help_text='Tutorial video URL', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'festival activities',
                'db_table': 'festival_activities',
                'ordering': ['festival', 'activity_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FestivalProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('points_earned', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, help_text='Optional notes or feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'festival progress',
                'db_table': 'festival_progress',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='festival',
            name='image_url',
            field=models.URLField(blank=True, help_text='Festival banner/image URL', null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='is_lunar_calendar',
            field=models.BooleanField(default=False, help_text='True if festival follows lunar calendar (dates vary)'),
        ),
        migrations.AddField(
            model_name='festival',
            name='name_gujarati',
            field=models.CharField(blank=True, help_text='Name in Gujarati', max_length=100),
        ),
        migrations.AddField(
            model_name='festival',
            name='name_hindi',
            field=models.CharField(blank=True, help_text='Name in Hindi', max_length=100),
        ),
        migrations.AddField(
            model_name='festival',
            name='name_malayalam',
            field=models.CharField(blank=True, help_text='Name in Malayalam', max_length=100),
        ),
        migrations.AddField(
            model_name='festival',
            name='name_punjabi',
            field=models.CharField(blank=True, help_text='Name in Punjabi', max_length=100),
        ),
        migrations.AddField(
            model_name='festival',
            name='name_tamil',
            field=models.CharField(blank=True, help_text='Name in Tamil', max_length=100),
        ),
        migrations.AddField(
            model_name='festival',
            name='name_telugu',
            field=models.CharField(blank=True, help_text='Name in Telugu', max_length=100),
        ),
        migrations.AddField(
            model_name='festival',
            name='significance',
            field=models.TextField(blank=True, help_text='Cultural/religious significance'),
        ),
        migrations.AddField(
            model_name='festival',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='festival',
            index=models.Index(fields=['is_active'], name='festivals_is_acti_0f9175_idx'),
        ),
        migrations.AddField(
            model_name='festivalactivity',
            name='festival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='festivals.festival'),
        ),
        migrations.AddField(
            model_name='festivalprogress',
            name='activity',
            field=models.ForeignKey(blank=True, help_text='Completed activity (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='festivals.festivalactivity'),
        ),
        migrations.AddField(
            model_name='festivalprogress',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='festival_progress', to='children.child'),
        ),
        migrations.AddField(
            model_name='festivalprogress',
            name='festival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_progress', to='festivals.festival'),
        ),
        migrations.AddField(
            model_name='festivalprogress',
            name='story',
            field=models.ForeignKey(blank=True, help_text='Completed story (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='festival_completions', to='stories.story'),
        ),
        migrations.AddIndex(
            model_name='festivalactivity',
            index=models.Index(fields=['festival', 'activity_type'], name='festival_ac_festiva_a26dd9_idx'),
        ),
        migrations.AddIndex(
            model_name='festivalactivity',
            index=models.Index(fields=['min_age', 'max_age'], name='festival_ac_min_age_2a5062_idx'),
        ),
        migrations.AddIndex(
            model_name='festivalactivity',
            index=models.Index(fields=['is_active'], name='festival_ac_is_acti_192f01_idx'),
        ),
        migrations.AddIndex(
            model_name='festivalprogress',
            index=models.Index(fields=['child', 'festival'], name='festival_pr_child_i_4f235e_idx'),
        ),
        migrations.AddIndex(
            model_name='festivalprogress',
            index=models.Index(fields=['child', 'is_completed'], name='festival_pr_child_i_021900_idx'),
        ),
        migrations.AddIndex(
            model_name='festivalprogress',
            index=models.Index(fields=['festival', 'is_completed'], name='festival_pr_festiva_3eeb4c_idx'),
        ),
    ]
