# Generated by Django 6.0 on 2025-12-18 00:00

import apps.certifications.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0003_child_peppi_addressing_child_peppi_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('certificate_type', models.CharField(choices=[('LEVEL_COMPLETION', 'Level Completion'), ('LANGUAGE_PROFICIENCY', 'Language Proficiency'), ('CULTURAL_KNOWLEDGE', 'Cultural Knowledge'), ('SPECIAL_ACHIEVEMENT', 'Special Achievement'), ('ANNUAL_PROGRESS', 'Annual Progress')], max_length=30)),
                ('template_html', models.TextField()),
                ('template_css', models.TextField(blank=True)),
                ('background_image', models.URLField(blank=True)),
                ('language', models.CharField(blank=True, help_text='Blank for all languages', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'certificate_templates',
            },
        ),
        migrations.CreateModel(
            name='AnnualProgressReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('report_data', models.JSONField(default=dict, help_text='Comprehensive yearly statistics')),
                ('starting_level', models.IntegerField(default=1)),
                ('ending_level', models.IntegerField(default=1)),
                ('total_stories_read', models.IntegerField(default=0)),
                ('total_points_earned', models.IntegerField(default=0)),
                ('total_time_minutes', models.IntegerField(default=0)),
                ('words_learned', models.IntegerField(default=0)),
                ('letters_mastered', models.IntegerField(default=0)),
                ('achievements_earned', models.JSONField(default=list)),
                ('monthly_breakdown', models.JSONField(default=dict)),
                ('pdf_url', models.URLField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_reports', to='children.child')),
            ],
            options={
                'db_table': 'annual_progress_reports',
                'unique_together': {('child', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PrintableCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_id', models.CharField(default=apps.certifications.models.generate_certificate_id, max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('achievement_data', models.JSONField(default=dict, help_text='Data used to populate certificate (level, scores, etc.)')),
                ('pdf_url', models.URLField(blank=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('share_url', models.URLField(blank=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printable_certificates', to='children.child')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_certificates', to='certifications.certificatetemplate')),
            ],
            options={
                'db_table': 'printable_certificates',
                'indexes': [models.Index(fields=['child', 'issued_date'], name='printable_c_child_i_da35bf_idx'), models.Index(fields=['certificate_id'], name='printable_c_certifi_7452ac_idx')],
            },
        ),
    ]
