# Generated by Django 6.0 on 2025-12-18 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0003_child_peppi_addressing_child_peppi_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CohortAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort_type', models.CharField(help_text='age_group, language, level, etc.', max_length=50)),
                ('cohort_value', models.CharField(max_length=50)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('active_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('churned_users', models.IntegerField(default=0)),
                ('average_session_duration', models.IntegerField(default=0)),
                ('average_sessions_per_user', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('retention_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'db_table': 'cohort_analytics',
                'indexes': [models.Index(fields=['cohort_type', 'period_start'], name='cohort_anal_cohort__0316e2_idx')],
            },
        ),
        migrations.CreateModel(
            name='LessonAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(max_length=50)),
                ('content_id', models.UUIDField()),
                ('language', models.CharField(max_length=20)),
                ('total_views', models.IntegerField(default=0)),
                ('unique_users', models.IntegerField(default=0)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('average_time_seconds', models.IntegerField(default=0)),
                ('drop_off_points', models.JSONField(default=dict, help_text='Page/section where users drop off')),
                ('difficulty_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('engagement_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'db_table': 'lesson_analytics',
                'indexes': [models.Index(fields=['content_type', 'language'], name='lesson_anal_content_16bb56_idx')],
                'unique_together': {('content_type', 'content_id')},
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('event_category', models.CharField(choices=[('NAVIGATION', 'Navigation'), ('CONTENT', 'Content Interaction'), ('GAMIFICATION', 'Gamification'), ('SOCIAL', 'Social'), ('SYSTEM', 'System'), ('ERROR', 'Error')], max_length=30)),
                ('event_name', models.CharField(max_length=100)),
                ('event_data', models.JSONField(default=dict)),
                ('page_url', models.CharField(blank=True, max_length=500)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('app_version', models.CharField(blank=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logs', to='children.child')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_logs',
                'indexes': [models.Index(fields=['user', 'timestamp'], name='event_logs_user_id_66612f_idx'), models.Index(fields=['event_category', 'event_name'], name='event_logs_event_c_f7f0b5_idx'), models.Index(fields=['session_id'], name='event_logs_session_0b424c_idx'), models.Index(fields=['timestamp'], name='event_logs_timesta_24e1a8_idx')],
            },
        ),
        migrations.CreateModel(
            name='PeppiAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('total_interactions', models.IntegerField(default=0)),
                ('voice_interactions', models.IntegerField(default=0)),
                ('text_interactions', models.IntegerField(default=0)),
                ('help_requests', models.IntegerField(default=0)),
                ('encouragements_given', models.IntegerField(default=0)),
                ('corrections_given', models.IntegerField(default=0)),
                ('topics_discussed', models.JSONField(default=list)),
                ('sentiment_scores', models.JSONField(default=dict)),
                ('average_response_time_ms', models.IntegerField(default=0)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peppi_analytics', to='children.child')),
            ],
            options={
                'db_table': 'peppi_analytics',
                'indexes': [models.Index(fields=['child', 'date'], name='peppi_analy_child_i_58bf48_idx')],
                'unique_together': {('child', 'date')},
            },
        ),
    ]
