# Generated by Django 5.2.9 on 2025-12-09 06:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('criteria_type', models.CharField(choices=[('STORIES_COMPLETED', 'Stories Completed'), ('STREAK_DAYS', 'Streak Days'), ('POINTS_EARNED', 'Points Earned'), ('TIME_SPENT_MINUTES', 'Time Spent'), ('VOICE_RECORDINGS', 'Voice Recordings'), ('LETTERS_MASTERED', 'Letters Mastered'), ('WORDS_MASTERED', 'Words Mastered')], max_length=30)),
                ('criteria_value', models.IntegerField()),
                ('display_order', models.IntegerField(default=0)),
                ('points_bonus', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'badges',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to='children.child')),
            ],
            options={
                'db_table': 'streaks',
            },
        ),
        migrations.CreateModel(
            name='ChildBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_badges', to='gamification.badge')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to='children.child')),
            ],
            options={
                'db_table': 'child_badges',
                'unique_together': {('child', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='VoiceRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('audio_url', models.URLField()),
                ('duration_ms', models.IntegerField()),
                ('transcription', models.TextField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_recordings', to='children.child')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stories.story')),
            ],
            options={
                'db_table': 'voice_recordings',
                'indexes': [models.Index(fields=['child', 'recorded_at'], name='voice_recor_child_i_1c5a68_idx')],
            },
        ),
    ]
