# Generated by Django 6.0 on 2025-12-27 07:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0005_add_fiji_hindi_language'),
        ('curriculum', '0011_verifiedletter_example_image'),
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallengeTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Unique identifier (e.g., "read_3_stories")', max_length=50, unique=True)),
                ('challenge_type', models.CharField(choices=[('story_read', 'Read Stories'), ('vocabulary', 'Learn Vocabulary'), ('voice_record', 'Voice Recording'), ('game_play', 'Play Games'), ('perfect_lesson', 'Perfect Lesson'), ('streak', 'Maintain Streak')], max_length=20)),
                ('title_english', models.CharField(max_length=200)),
                ('description_english', models.TextField()),
                ('icon', models.CharField(default='star', max_length=50)),
                ('target', models.IntegerField(help_text='Target value to complete (e.g., 3 for "read 3 stories")')),
                ('xp_reward', models.IntegerField(default=50)),
                ('coin_reward', models.IntegerField(default=100)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('min_level', models.IntegerField(default=1, help_text='Minimum child level to receive this challenge')),
                ('max_level', models.IntegerField(default=10, help_text='Maximum child level to receive this challenge')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'daily_challenge_templates',
                'ordering': ['difficulty', 'code'],
                'indexes': [models.Index(fields=['challenge_type', 'difficulty'], name='daily_chall_challen_412692_idx'), models.Index(fields=['min_level', 'max_level'], name='daily_chall_min_lev_a7c211_idx')],
            },
        ),
        migrations.CreateModel(
            name='PeppiAccessory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Unique identifier (e.g., "party_hat", "flower_crown")', max_length=50, unique=True)),
                ('name_english', models.CharField(max_length=100)),
                ('slot', models.CharField(choices=[('head', 'Head'), ('neck', 'Neck'), ('paws', 'Paws'), ('tail', 'Tail'), ('background', 'Background')], max_length=20)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('unlock_type', models.CharField(choices=[('default', 'Default (Available from Start)'), ('streak_days', 'Streak Days'), ('stories_completed', 'Stories Completed'), ('vocabulary_mastered', 'Vocabulary Mastered'), ('level', 'Level Reached'), ('perfect_scores', 'Perfect Scores'), ('festival', 'Festival Event'), ('language_specific', 'Language-Specific Achievement'), ('recordings', 'Voice Recordings'), ('games_won', 'Games Won'), ('badges_earned', 'Badges Earned'), ('alphabet_mastered', 'Alphabet Mastered'), ('special_event', 'Special Event')], default='default', max_length=30)),
                ('unlock_value', models.IntegerField(default=0)),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'peppi_accessories',
                'ordering': ['slot', 'name_english'],
                'indexes': [models.Index(fields=['slot', 'rarity'], name='peppi_acces_slot_d7a958_idx'), models.Index(fields=['unlock_type'], name='peppi_acces_unlock__cbdbd9_idx')],
            },
        ),
        migrations.CreateModel(
            name='PeppiOutfit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Unique identifier code (e.g., "hindi_kurta", "diwali_special")', max_length=50, unique=True)),
                ('name_english', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('traditional', 'Traditional'), ('festive', 'Festive'), ('dance', 'Dance'), ('silly', 'Silly'), ('legendary', 'Legendary'), ('accessory', 'Accessory')], max_length=20)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('primary_language', models.CharField(blank=True, choices=[('HINDI', 'Hindi'), ('TAMIL', 'Tamil'), ('GUJARATI', 'Gujarati'), ('PUNJABI', 'Punjabi'), ('TELUGU', 'Telugu'), ('MALAYALAM', 'Malayalam'), ('FIJI_HINDI', 'Fiji Hindi')], help_text='If language-specific, which language this belongs to', max_length=20, null=True)),
                ('unlock_type', models.CharField(choices=[('default', 'Default (Available from Start)'), ('streak_days', 'Streak Days'), ('stories_completed', 'Stories Completed'), ('vocabulary_mastered', 'Vocabulary Mastered'), ('level', 'Level Reached'), ('perfect_scores', 'Perfect Scores'), ('festival', 'Festival Event'), ('language_specific', 'Language-Specific Achievement'), ('recordings', 'Voice Recordings'), ('games_won', 'Games Won'), ('badges_earned', 'Badges Earned'), ('alphabet_mastered', 'Alphabet Mastered'), ('special_event', 'Special Event')], default='default', max_length=30)),
                ('unlock_value', models.IntegerField(default=0, help_text='Value required to unlock (e.g., 7 for 7-day streak)')),
                ('unlock_festival', models.CharField(blank=True, help_text='Festival code if unlock_type is FESTIVAL', max_length=50)),
                ('image_url', models.URLField(blank=True, help_text='Full outfit image URL')),
                ('thumbnail_url', models.URLField(blank=True, help_text='Thumbnail preview URL')),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'peppi_outfits',
                'ordering': ['sort_order', 'name_english'],
                'indexes': [models.Index(fields=['category', 'rarity'], name='peppi_outfi_categor_509389_idx'), models.Index(fields=['unlock_type'], name='peppi_outfi_unlock__48e5f9_idx'), models.Index(fields=['primary_language'], name='peppi_outfi_primary_d2eb62_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChildUnlockedPhrase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('is_new', models.BooleanField(default=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_phrases', to='children.child')),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_by_children', to='curriculum.peppiphrase')),
            ],
            options={
                'db_table': 'child_unlocked_phrases',
                'indexes': [models.Index(fields=['child', 'unlocked_at'], name='child_unloc_child_i_9c9e07_idx'), models.Index(fields=['is_new'], name='child_unloc_is_new_02107c_idx')],
                'unique_together': {('child', 'phrase')},
            },
        ),
        migrations.CreateModel(
            name='ChildDailyChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='Date this challenge was assigned')),
                ('progress', models.IntegerField(default=0, help_text='Current progress towards target')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reward_claimed', models.BooleanField(default=False, help_text='Whether rewards have been claimed')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_challenges', to='children.child')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_challenges', to='gamification.dailychallengetemplate')),
            ],
            options={
                'db_table': 'child_daily_challenges',
                'indexes': [models.Index(fields=['child', 'date'], name='child_daily_child_i_fd20c9_idx'), models.Index(fields=['is_completed', 'reward_claimed'], name='child_daily_is_comp_11570d_idx')],
                'unique_together': {('child', 'template', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ChildUnlockedAccessory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('is_new', models.BooleanField(default=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_accessories', to='children.child')),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_by_children', to='gamification.peppiaccessory')),
            ],
            options={
                'db_table': 'child_unlocked_accessories',
                'indexes': [models.Index(fields=['child', 'unlocked_at'], name='child_unloc_child_i_bbea40_idx'), models.Index(fields=['is_new'], name='child_unloc_is_new_a46080_idx')],
                'unique_together': {('child', 'accessory')},
            },
        ),
        migrations.CreateModel(
            name='ChildEquippedAccessories',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.CharField(choices=[('head', 'Head'), ('neck', 'Neck'), ('paws', 'Paws'), ('tail', 'Tail'), ('background', 'Background')], max_length=20)),
                ('equipped_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipped_accessories', to='children.child')),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipped_by_children', to='gamification.peppiaccessory')),
            ],
            options={
                'db_table': 'child_equipped_accessories',
                'indexes': [models.Index(fields=['child', 'slot'], name='child_equip_child_i_6367e4_idx')],
                'unique_together': {('child', 'slot')},
            },
        ),
        migrations.CreateModel(
            name='ChildUnlockedOutfit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('is_new', models.BooleanField(default=True, help_text='Whether child has seen this unlock yet')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_outfits', to='children.child')),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_by_children', to='gamification.peppioutfit')),
            ],
            options={
                'db_table': 'child_unlocked_outfits',
                'indexes': [models.Index(fields=['child', 'unlocked_at'], name='child_unloc_child_i_9f39b7_idx'), models.Index(fields=['is_new'], name='child_unloc_is_new_42a05f_idx')],
                'unique_together': {('child', 'outfit')},
            },
        ),
        migrations.CreateModel(
            name='ChildPeppiState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('happiness', models.IntegerField(default=80, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('hunger', models.IntegerField(default=50, help_text='Lower is hungrier', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('evolution_stage', models.CharField(choices=[('kitten', 'Kitten'), ('young_cat', 'Young Cat'), ('adult_cat', 'Adult Cat'), ('wise_cat', 'Wise Cat')], default='kitten', max_length=20)),
                ('coins', models.IntegerField(default=100)),
                ('gems', models.IntegerField(default=0)),
                ('total_pets', models.IntegerField(default=0)),
                ('last_fed_at', models.DateTimeField(blank=True, null=True)),
                ('last_played_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='peppi_state', to='children.child')),
                ('current_outfit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_children', to='gamification.peppioutfit')),
            ],
            options={
                'db_table': 'child_peppi_states',
                'indexes': [models.Index(fields=['evolution_stage'], name='child_peppi_evoluti_735240_idx')],
            },
        ),
        migrations.CreateModel(
            name='PeppiOutfitTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('HINDI', 'Hindi'), ('TAMIL', 'Tamil'), ('GUJARATI', 'Gujarati'), ('PUNJABI', 'Punjabi'), ('TELUGU', 'Telugu'), ('MALAYALAM', 'Malayalam'), ('FIJI_HINDI', 'Fiji Hindi')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='gamification.peppioutfit')),
            ],
            options={
                'db_table': 'peppi_outfit_translations',
                'indexes': [models.Index(fields=['outfit', 'language'], name='peppi_outfi_outfit__a267a9_idx')],
                'unique_together': {('outfit', 'language')},
            },
        ),
    ]
