# Generated by Django 5.2.9 on 2026-01-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gamification", "0002_peppi_gamification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="badge",
            options={"ordering": ["category", "display_order"]},
        ),
        migrations.AddField(
            model_name="badge",
            name="available_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badge",
            name="available_until",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badge",
            name="category",
            field=models.CharField(
                choices=[
                    ("ACHIEVEMENT", "Achievement"),
                    ("SKILL", "Skill"),
                    ("SOCIAL", "Social"),
                    ("STREAK", "Streak"),
                    ("SPECIAL", "Special"),
                    ("SEASONAL", "Seasonal"),
                ],
                default="ACHIEVEMENT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="badge",
            name="criteria_extra",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="badge",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="badge",
            name="is_seasonal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="badge",
            name="rarity",
            field=models.CharField(
                choices=[
                    ("COMMON", "Common"),
                    ("UNCOMMON", "Uncommon"),
                    ("RARE", "Rare"),
                    ("EPIC", "Epic"),
                    ("LEGENDARY", "Legendary"),
                ],
                default="COMMON",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="badge",
            name="criteria_type",
            field=models.CharField(
                choices=[
                    ("STORIES_COMPLETED", "Stories Completed"),
                    ("STREAK_DAYS", "Streak Days"),
                    ("POINTS_EARNED", "Points Earned"),
                    ("TIME_SPENT_MINUTES", "Time Spent"),
                    ("VOICE_RECORDINGS", "Voice Recordings"),
                    ("LETTERS_MASTERED", "Letters Mastered"),
                    ("WORDS_MASTERED", "Words Mastered"),
                    ("CHALLENGES_COMPLETED", "Challenges Completed"),
                    ("CHALLENGES_WON", "Challenges Won"),
                    ("CHALLENGE_WIN_STREAK", "Challenge Win Streak"),
                    ("PERFECT_CHALLENGES", "Perfect Challenges"),
                    ("UNDERDOG_WINS", "Underdog Wins"),
                    ("GIANT_SLAYER", "Giant Slayer Wins"),
                    ("FRIENDS_INVITED", "Friends Invited"),
                    ("FRIENDS_CONVERTED", "Friends Converted to Users"),
                    ("MULTIPLAYER_GAMES", "Multiplayer Games"),
                    ("RATING_ACHIEVED", "Rating Achieved"),
                    ("ACCURACY_ACHIEVED", "Accuracy Percentage"),
                ],
                max_length=30,
            ),
        ),
    ]
