# Generated by Django 6.0 on 2025-12-18 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0003_child_peppi_addressing_child_peppi_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflinePackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('package_type', models.CharField(choices=[('FREE_TIER', 'Free Tier Package'), ('LANGUAGE_PACK', 'Language Pack'), ('CURRICULUM_MODULE', 'Curriculum Module'), ('FESTIVAL_PACK', 'Festival Pack')], default='FREE_TIER', max_length=30)),
                ('language', models.CharField(max_length=20)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('size_mb', models.DecimalField(decimal_places=2, max_digits=8)),
                ('content_manifest', models.JSONField(default=dict, help_text='JSON manifest of included stories, audio, images')),
                ('is_active', models.BooleanField(default=True)),
                ('min_app_version', models.CharField(default='1.0.0', max_length=20)),
            ],
            options={
                'db_table': 'offline_packages',
                'indexes': [models.Index(fields=['language', 'package_type'], name='offline_pac_languag_8021d9_idx'), models.Index(fields=['is_active'], name='offline_pac_is_acti_847ef3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChildOfflineContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pending Sync'), ('SYNCED', 'Synced'), ('FAILED', 'Sync Failed')], default='PENDING', max_length=20)),
                ('offline_progress', models.JSONField(default=dict, help_text='Progress made while offline')),
                ('storage_used_mb', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_content', to='children.child')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='offline.offlinepackage')),
            ],
            options={
                'db_table': 'child_offline_content',
                'indexes': [models.Index(fields=['child', 'sync_status'], name='child_offli_child_i_5f16c4_idx')],
                'unique_together': {('child', 'package')},
            },
        ),
    ]
