# Generated by Django 6.0 on 2026-01-26 02:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Organization name', max_length=255)),
                ('slug', models.SlugField(help_text='URL-safe identifier', max_length=100, unique=True)),
                ('domain', models.CharField(blank=True, help_text='Custom domain for this tenant (e.g., school.peppiacademy.com)', max_length=255, null=True, unique=True)),
                ('logo_url', models.URLField(blank=True, help_text='Tenant logo URL', null=True)),
                ('theme_config', models.JSONField(blank=True, default=dict, help_text='Custom theme configuration (colors, branding)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
