# Generated by Django 6.0 on 2025-12-18 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0003_child_peppi_addressing_child_peppi_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('session_type', models.CharField(choices=[('ONE_ON_ONE', 'One-on-One'), ('GROUP', 'Group Session'), ('CULTURAL_EVENT', 'Cultural Event')], default='ONE_ON_ONE', max_length=20)),
                ('language', models.CharField(max_length=20)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='SCHEDULED', max_length=20)),
                ('max_participants', models.IntegerField(default=1)),
                ('meeting_url', models.URLField(blank=True)),
                ('recording_url', models.URLField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
            options={
                'db_table': 'live_sessions',
            },
        ),
        migrations.CreateModel(
            name='SessionModerationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('WARNING', 'Warning Issued'), ('MUTED', 'User Muted'), ('REMOVED', 'User Removed'), ('SESSION_ENDED', 'Session Ended')], max_length=20)),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to='live_classes.livesession')),
                ('target_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'session_moderation_logs',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('profile_image', models.URLField(blank=True)),
                ('languages', models.JSONField(default=list, help_text='List of language codes')),
                ('specializations', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive')], default='PENDING', max_length=20)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_students', models.IntegerField(default=0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
        migrations.AddField(
            model_name='livesession',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='live_classes.teacher'),
        ),
        migrations.CreateModel(
            name='TeacherCertification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('issuing_organization', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('credential_url', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='live_classes.teacher')),
            ],
            options={
                'db_table': 'teacher_certifications',
            },
        ),
        migrations.CreateModel(
            name='TeacherPerformanceMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.DateField(help_text='First day of the month')),
                ('sessions_conducted', models.IntegerField(default=0)),
                ('total_students', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('attendance_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('complaints', models.IntegerField(default=0)),
                ('positive_reviews', models.IntegerField(default=0)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='live_classes.teacher')),
            ],
            options={
                'db_table': 'teacher_performance_metrics',
            },
        ),
        migrations.CreateModel(
            name='SessionParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('ATTENDED', 'Attended'), ('NO_SHOW', 'No Show'), ('CANCELLED', 'Cancelled')], default='REGISTERED', max_length=20)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='children.child')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='live_classes.livesession')),
            ],
            options={
                'db_table': 'session_participants',
                'unique_together': {('session', 'child')},
            },
        ),
        migrations.CreateModel(
            name='SessionRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(help_text='1-5 star rating')),
                ('feedback', models.TextField(blank=True)),
                ('would_recommend', models.BooleanField(default=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_ratings', to='children.child')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_ratings', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='live_classes.livesession')),
            ],
            options={
                'db_table': 'session_ratings',
                'unique_together': {('session', 'child')},
            },
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['status', 'rating'], name='teachers_status_6d5946_idx'),
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['teacher', 'scheduled_start'], name='live_sessio_teacher_2b4846_idx'),
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['status', 'scheduled_start'], name='live_sessio_status_035d02_idx'),
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['language'], name='live_sessio_languag_355bb0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherperformancemetrics',
            unique_together={('teacher', 'month')},
        ),
    ]
